#!/bin/sh
set -e

# Substitute secrets from environment variables
cp /build/config-template.yaml /build/pkg/opt/clash/config.yaml
sed -i "s|__WARP_PRIVATE_KEY__|${WARP_PRIVATE_KEY}|g" /build/pkg/opt/clash/config.yaml
sed -i "s|__BLANC_SUBSCRIPTION_URL__|${BLANC_SUBSCRIPTION_URL}|g" /build/pkg/opt/clash/config.yaml

echo "[*] Config patched with secrets"

# Apply patches
/build/patch.sh

# Create .PKGINFO for apk mkpkg
cat > /build/pkg/.PKGINFO << 'EOF'
# Generated by custom build
pkgname = luci-app-ssclash
pkgver = 4.5.1-r1-custom
pkgdesc = LuCI interface for SSClash (custom config + auto kernel download)
url = https://github.com/zerolabnet/ssclash
builddate = 1700000000
packager = Custom Build
size = 4075520
arch = noarch
origin = ssclash
license = MIT
EOF

# Build APK v3
echo "[*] Building custom APK..."
apk mkpkg --files /build/pkg -o /output/luci-app-ssclash-4.5.1-r1-custom.apk

echo "[*] Done!"
ls -lh /output/luci-app-ssclash-4.5.1-r1-custom.apk
